from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

BASE_DIR = Path(__file__).resolve().parent
# Raw source exported from Kaggle-style dataset.
RAW_FILE = BASE_DIR / "Ecommerce_Delivery_Analytics_New.csv"
# Cleaned analytical table generated by this script.
CLEAN_FILE = BASE_DIR / "food_delivery.csv"
# Text report with metrics and recommendations.
REPORT_FILE = BASE_DIR / "analysis_summary.md"
# Folder where all charts are written.
FIGURE_DIR = BASE_DIR / "outputs"

COLUMN_MAP = {
    "Order ID": "order_id",
    "Customer ID": "customer_id",
    "Platform": "platform",
    "Order Date & Time": "order_time_raw",
    "Delivery Time (Minutes)": "delivery_duration_min",
    "Product Category": "product_category",
    "Order Value (INR)": "order_value_inr",
    "Customer Feedback": "customer_feedback",
    "Service Rating": "rating",
    "Delivery Delay": "delivery_delay",
    "Refund Requested": "refund_requested",
}


def load_data(path: Path) -> pd.DataFrame:
    # Centralized CSV reader so source switching is simple.
    return pd.read_csv(path)


def _parse_order_time_to_minutes(series: pd.Series) -> pd.Series:
    # Source values look like MM:SS.s (for example: 19:29.5), so convert to minutes after 00:00.
    formatted = "00:" + series.astype("string").str.strip()
    td = pd.to_timedelta(formatted, errors="coerce")
    return td.dt.total_seconds() / 60


def clean_data(df: pd.DataFrame) -> pd.DataFrame:
    # Rename source columns to consistent snake_case names used across analysis.
    cleaned = df.rename(columns=COLUMN_MAP).copy()

    if "order_id" in cleaned.columns:
        # Trim IDs and remove duplicate order rows to keep one record per order.
        cleaned["order_id"] = cleaned["order_id"].astype("string").str.strip()
        cleaned = cleaned.drop_duplicates(subset=["order_id"], keep="first")

    for numeric_col in ["delivery_duration_min", "order_value_inr", "rating"]:
        # Force numeric parsing; invalid strings become NaN for safe downstream math.
        if numeric_col in cleaned.columns:
            cleaned[numeric_col] = pd.to_numeric(cleaned[numeric_col], errors="coerce")

    if "order_time_raw" in cleaned.columns:
        # Convert time-like raw values into minute-of-day and hour features.
        cleaned["order_minute_of_day"] = _parse_order_time_to_minutes(cleaned["order_time_raw"])
        cleaned["order_hour"] = np.floor(cleaned["order_minute_of_day"] / 60).astype("Int64")

    if "delivery_delay" in cleaned.columns:
        cleaned["delivery_delay"] = cleaned["delivery_delay"].astype("string").str.strip().str.title()

    if "refund_requested" in cleaned.columns:
        cleaned["refund_requested"] = cleaned["refund_requested"].astype("string").str.strip().str.title()

    if "delivery_duration_min" in cleaned.columns:
        # Operational SLA-style label: >30 min considered late.
        cleaned["delay_category"] = np.where(cleaned["delivery_duration_min"].gt(30), "Late", "On-Time")

    if {"delivery_delay", "delay_category"}.issubset(cleaned.columns):
        # If the source explicitly flags delay as Yes, force category to Late.
        delayed_flag = cleaned["delivery_delay"].eq("Yes")
        cleaned["delay_category"] = np.where(delayed_flag, "Late", cleaned["delay_category"])

    if "delivery_duration_min" in cleaned.columns:
        # Bucket duration to analyze refund/quality behavior by service speed bands.
        cleaned["duration_band"] = pd.cut(
            cleaned["delivery_duration_min"],
            bins=[-np.inf, 15, 30, 45, 60, np.inf],
            labels=["<=15", "15-30", "30-45", "45-60", ">60"],
            right=True,
        )

    if "rating" in cleaned.columns:
        # Bucket rating into business-friendly quality tiers.
        cleaned["rating_band"] = pd.cut(
            cleaned["rating"],
            bins=[0, 2, 3, 4, 5],
            labels=["Low (1-2)", "Mid (3)", "Good (4)", "Excellent (5)"],
            include_lowest=True,
            right=True,
        )

    required_non_null = [
        col
        for col in ["order_id", "delivery_duration_min", "rating", "platform", "product_category"]
        if col in cleaned.columns
    ]
    if required_non_null:
        # Remove rows that cannot support core KPI and segmentation analysis.
        cleaned = cleaned.dropna(subset=required_non_null)

    preferred_order = [
        "order_id",
        "customer_id",
        "platform",
        "product_category",
        "order_time_raw",
        "order_minute_of_day",
        "order_hour",
        "delivery_duration_min",
        "delivery_delay",
        "delay_category",
        "rating",
        "rating_band",
        "order_value_inr",
        "refund_requested",
        "duration_band",
        "customer_feedback",
    ]
    existing_order = [column for column in preferred_order if column in cleaned.columns]
    remaining_columns = [column for column in cleaned.columns if column not in existing_order]
    # Return preferred column order first, then any additional columns.
    return cleaned[existing_order + remaining_columns]


def write_summary(cleaned: pd.DataFrame, raw: pd.DataFrame, output_path: Path) -> str:
    # Boolean mask used repeatedly for Late vs On-Time comparisons.
    late_mask = cleaned.get("delay_category", pd.Series(index=cleaned.index, dtype="object")).eq("Late")

    avg_rating_late = cleaned.loc[late_mask, "rating"].mean() if "rating" in cleaned.columns else float("nan")
    avg_rating_ontime = cleaned.loc[~late_mask, "rating"].mean() if "rating" in cleaned.columns else float("nan")

    duration_rating_corr = float("nan")
    if {"delivery_duration_min", "rating"}.issubset(cleaned.columns):
        duration_rating_corr = cleaned[["delivery_duration_min", "rating"]].corr().iloc[0, 1]

    delay_refund_rate = float("nan")
    ontime_refund_rate = float("nan")
    if {"refund_requested", "delay_category"}.issubset(cleaned.columns):
        refund_yes = cleaned["refund_requested"].eq("Yes")
        delay_refund_rate = refund_yes[late_mask].mean() * 100 if late_mask.any() else float("nan")
        ontime_refund_rate = refund_yes[~late_mask].mean() * 100 if (~late_mask).any() else float("nan")

    lines: list[str] = []
    # Build report as markdown lines, then write once at the end.
    lines.append("# Food Delivery Delay & Rating Analysis")
    lines.append("")
    lines.append("## Data Cleaning")
    lines.append(f"- Raw rows: {len(raw):,}")
    lines.append(f"- Cleaned rows: {len(cleaned):,}")
    lines.append(f"- Duplicate order IDs removed: {int(raw['Order ID'].duplicated().sum()):,}")
    lines.append("- Columns were standardized to snake_case and key fields were converted to numeric types")
    lines.append("- Delay category is derived using delivery time (>30 min = Late) and Delivery Delay flag")
    lines.append("")
    lines.append("## Core Findings")
    lines.append(f"- Average delivery duration: {cleaned['delivery_duration_min'].mean():.2f} minutes")
    lines.append(f"- Average service rating: {cleaned['rating'].mean():.2f} / 5")
    lines.append(f"- Share of late orders: {(late_mask.mean() * 100):.2f}%")
    lines.append(f"- Average rating (On-Time): {avg_rating_ontime:.2f}")
    lines.append(f"- Average rating (Late): {avg_rating_late:.2f}")
    lines.append(f"- Correlation between delivery duration and rating: {duration_rating_corr:.4f}")

    if np.isfinite(delay_refund_rate) and np.isfinite(ontime_refund_rate):
        lines.append(f"- Refund rate for Late orders: {delay_refund_rate:.2f}%")
        lines.append(f"- Refund rate for On-Time orders: {ontime_refund_rate:.2f}%")

    if "platform" in cleaned.columns:
        # Find platform with worst average delivery time for prioritization.
        platform_stats = (
            cleaned.groupby("platform", dropna=False)
            .agg(avg_delivery_minutes=("delivery_duration_min", "mean"), avg_rating=("rating", "mean"))
            .sort_values("avg_delivery_minutes", ascending=False)
        )
        slowest_platform = platform_stats.index[0]
        lines.append(
            f"- Platform with highest average delivery time: {slowest_platform} ({platform_stats.iloc[0]['avg_delivery_minutes']:.2f} min)"
        )

    lines.append("")
    lines.append("## Time-Based Analysis")
    if {"order_hour", "delivery_duration_min"}.issubset(cleaned.columns):
        # Hourly aggregate for identifying busy and delay-prone windows.
        hourly = (
            cleaned.groupby("order_hour", dropna=True)
            .agg(
                orders=("order_id", "count"),
                avg_delay_min=("delivery_duration_min", "mean"),
            )
            .dropna()
            .sort_index()
        )
        if not hourly.empty:
            peak_delay_hour = int(hourly["avg_delay_min"].idxmax())
            peak_delay_value = float(hourly.loc[peak_delay_hour, "avg_delay_min"])
            lines.append(f"- Peak average delay hour: {peak_delay_hour:02d}:00 ({peak_delay_value:.2f} min)")
            top_hours = hourly.sort_values("orders", ascending=False).head(3)
            lines.append(
                "- Top 3 order volume hours: "
                + ", ".join([f"{int(h):02d}:00 ({int(v)} orders)" for h, v in top_hours["orders"].items()])
            )

            if hourly.index.nunique() <= 1 and "order_minute_of_day" in cleaned.columns:
                # Fallback granularity when hour feature collapses into one bucket.
                lines.append("- Note: source order time appears to be minute-second format, so hourly spread is limited")
                minute_bucket = (
                    cleaned.assign(minute_bucket=(cleaned["order_minute_of_day"] // 5 * 5).astype("Int64"))
                    .groupby("minute_bucket", dropna=True)
                    .agg(
                        orders=("order_id", "count"),
                        avg_delay_min=("delivery_duration_min", "mean"),
                    )
                    .dropna()
                    .sort_index()
                )
                if not minute_bucket.empty:
                    peak_min_bucket = int(minute_bucket["avg_delay_min"].idxmax())
                    lines.append(
                        f"- Peak 5-minute bucket by delay: {peak_min_bucket:02d}-{peak_min_bucket + 4:02d} min ({minute_bucket.loc[peak_min_bucket, 'avg_delay_min']:.2f} min)"
                    )

    lines.append("")
    lines.append("## Product Category Analysis")
    if {"product_category", "delivery_duration_min", "rating"}.issubset(cleaned.columns):
        # Category-level means highlight slowest and lowest-rated segments.
        category_stats = (
            cleaned.groupby("product_category", dropna=False)[["delivery_duration_min", "rating"]]
            .mean()
            .sort_values("delivery_duration_min", ascending=False)
        )
        if not category_stats.empty:
            highest_delay_category = category_stats.index[0]
            lowest_rating_category = category_stats["rating"].idxmin()
            lines.append(
                f"- Category with highest average delay: {highest_delay_category} ({category_stats.iloc[0]['delivery_duration_min']:.2f} min)"
            )
            lines.append(
                f"- Category with lowest average rating: {lowest_rating_category} ({category_stats.loc[lowest_rating_category, 'rating']:.2f})"
            )

    lines.append("")
    lines.append("## Order Value vs Rating")
    if {"order_value_inr", "rating"}.issubset(cleaned.columns):
        # Check whether higher basket value relates to better service sentiment.
        value_rating_corr = cleaned[["order_value_inr", "rating"]].corr().iloc[0, 1]
        lines.append(f"- Correlation between order value and rating: {value_rating_corr:.4f}")
        value_band = pd.qcut(cleaned["order_value_inr"], q=4, duplicates="drop")
        value_segment_rating = cleaned.assign(value_band=value_band).groupby("value_band", observed=False)["rating"].mean()
        if not value_segment_rating.empty:
            best_band = value_segment_rating.idxmax()
            lines.append(f"- Best rated order value segment: {best_band} ({value_segment_rating.max():.2f})")

    lines.append("")
    lines.append("## Refund Analysis")
    if {"refund_requested", "rating", "delivery_duration_min", "delay_category"}.issubset(cleaned.columns):
        # Compare rating and refund behavior across delay states.
        refund_yes = cleaned["refund_requested"].eq("Yes")
        refund_rating = cleaned.groupby(refund_yes, dropna=False)["rating"].mean()
        if True in refund_rating.index and False in refund_rating.index:
            lines.append(f"- Avg rating when refund requested: {refund_rating.loc[True]:.2f}")
            lines.append(f"- Avg rating when no refund requested: {refund_rating.loc[False]:.2f}")

        refund_by_delay = (
            cleaned.assign(refund_yes=refund_yes.astype(int))
            .groupby("delay_category", dropna=False)["refund_yes"]
            .mean()
            .mul(100)
        )
        if {"Late", "On-Time"}.issubset(refund_by_delay.index):
            lift = refund_by_delay.loc["Late"] / refund_by_delay.loc["On-Time"] if refund_by_delay.loc["On-Time"] else np.nan
            lines.append(
                f"- Refund rate Late vs On-Time: {refund_by_delay.loc['Late']:.2f}% vs {refund_by_delay.loc['On-Time']:.2f}%"
            )
            if np.isfinite(lift):
                lines.append(f"- Late orders have {lift:.2f}x higher refund rate than On-Time orders")

    lines.append("")
    lines.append("## Baseline ML Model (Predict Rating)")
    ml_note = "- Baseline linear regression was skipped because required dependencies/features were unavailable"
    if {"delivery_duration_min", "rating"}.issubset(cleaned.columns):
        try:
            # Lightweight baseline to quantify directional impact of delay on rating.
            from sklearn.linear_model import LinearRegression
            from sklearn.metrics import mean_absolute_error, r2_score
            from sklearn.model_selection import train_test_split

            model_df = cleaned[["delivery_duration_min", "rating"]].dropna()
            if len(model_df) > 20:
                X = model_df[["delivery_duration_min"]]
                y = model_df["rating"]
                X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
                model = LinearRegression()
                model.fit(X_train, y_train)
                preds = model.predict(X_test)
                r2 = r2_score(y_test, preds)
                mae = mean_absolute_error(y_test, preds)
                lines.append(f"- Model: LinearRegression (features: delivery_duration_min)")
                lines.append(f"- Test MAE: {mae:.4f}")
                lines.append(f"- Test R^2: {r2:.4f}")
                lines.append(
                    f"- Estimated rating change per +1 minute delivery time: {float(model.coef_[0]):.4f}"
                )
            else:
                lines.append("- Not enough non-null rows to train/test the baseline model")
        except Exception:
            lines.append(ml_note)

    lines.append("")
    lines.append("## Business Recommendations")
    lines.append("- If predicted or observed delivery exceeds 30 minutes, trigger proactive apology coupon communication")
    lines.append("- Prioritize high-delay product categories for dispatch optimization and packaging process fixes")
    lines.append("- Increase delivery partner availability during peak delay hours to reduce backlog")
    lines.append("- Use refund-risk monitoring for late orders to trigger faster support intervention")
    lines.append("- Track value-segment experience to ensure high-value customers receive consistently high service")
    lines.append("")
    lines.append("## Data Limitations")
    lines.append("- This dataset does not include delivery distance, restaurant prep time, delivery partner ID, or city-level location")
    lines.append("- Order Date & Time appears to be a time-like value rather than full timestamp, limiting temporal trend depth")

    output_path.write_text("\n".join(lines), encoding="utf-8")
    return "\n".join(lines)


def make_plots(cleaned: pd.DataFrame) -> None:
    try:
        import matplotlib
        import matplotlib.pyplot as plt
        import seaborn as sns
    except Exception as exc:
        print(f"Skipping plot generation because plotting libraries are unavailable: {exc}")
        return

    matplotlib.use("Agg")
    # Ensure output directory exists before writing figures.
    FIGURE_DIR.mkdir(exist_ok=True)
    sns.set_theme(style="whitegrid")

    plt.figure(figsize=(8, 4))
    sns.countplot(data=cleaned, x="rating", order=sorted(cleaned["rating"].dropna().unique()), color="#2563eb")
    plt.title("Rating Distribution")
    plt.xlabel("Service Rating")
    plt.ylabel("Orders")
    plt.tight_layout()
    plt.savefig(FIGURE_DIR / "rating_distribution.png", dpi=150)
    plt.close()

    plt.figure(figsize=(8, 4))
    sns.histplot(cleaned["delivery_duration_min"], bins=30, kde=True, color="#0f766e")
    plt.title("Delivery Duration Distribution")
    plt.xlabel("Delivery Duration (minutes)")
    plt.ylabel("Orders")
    plt.tight_layout()
    plt.savefig(FIGURE_DIR / "delivery_duration_distribution.png", dpi=150)
    plt.close()

    sample = cleaned.sample(min(len(cleaned), 5000), random_state=42)
    # Sample cap keeps scatter rendering performant on large datasets.
    plt.figure(figsize=(8, 5))
    sns.scatterplot(data=sample, x="delivery_duration_min", y="rating", hue="delay_category", alpha=0.5)
    plt.title("Delivery Duration vs Rating")
    plt.xlabel("Delivery Duration (minutes)")
    plt.ylabel("Rating")
    plt.tight_layout()
    plt.savefig(FIGURE_DIR / "delivery_duration_vs_rating_scatter.png", dpi=150)
    plt.close()

    plt.figure(figsize=(8, 5))
    sns.boxplot(
        data=cleaned,
        x="delay_category",
        y="rating",
        hue="delay_category",
        order=["On-Time", "Late"],
        palette="viridis",
    )
    plt.title("Delay Category vs Rating")
    plt.xlabel("Delay Category")
    plt.ylabel("Rating")
    plt.tight_layout()
    plt.savefig(FIGURE_DIR / "delay_category_vs_rating_boxplot.png", dpi=150)
    plt.close()

    if {"order_hour", "delivery_duration_min", "order_id"}.issubset(cleaned.columns):
        # Build temporal aggregates for hourly demand and delay charts.
        hourly = (
            cleaned.groupby("order_hour", dropna=True)
            .agg(
                orders=("order_id", "count"),
                avg_delay_min=("delivery_duration_min", "mean"),
            )
            .dropna()
            .sort_index()
            .reset_index()
        )
        if not hourly.empty:
            hourly["order_hour"] = pd.to_numeric(hourly["order_hour"], errors="coerce")
            hourly["avg_delay_min"] = pd.to_numeric(hourly["avg_delay_min"], errors="coerce")
            hourly = hourly.dropna(subset=["order_hour", "avg_delay_min"])

            plt.figure(figsize=(10, 4))
            sns.barplot(data=hourly, x="order_hour", y="orders", color="#1d4ed8")
            plt.title("Orders per Hour")
            plt.xlabel("Order Hour")
            plt.ylabel("Orders")
            plt.tight_layout()
            plt.savefig(FIGURE_DIR / "orders_per_hour.png", dpi=150)
            plt.close()

            plt.figure(figsize=(10, 4))
            plt.plot(hourly["order_hour"], hourly["avg_delay_min"], marker="o", color="#b91c1c")
            plt.title("Average Delay per Hour")
            plt.xlabel("Order Hour")
            plt.ylabel("Average Delivery Duration (min)")
            plt.tight_layout()
            plt.savefig(FIGURE_DIR / "avg_delay_per_hour.png", dpi=150)
            plt.close()

            if hourly["order_hour"].nunique() <= 1 and "order_minute_of_day" in cleaned.columns:
                # Additional time-bucket fallback when hour lacks variation.
                minute_bucket = (
                    cleaned.assign(minute_bucket=(cleaned["order_minute_of_day"] // 5 * 5).astype("Int64"))
                    .groupby("minute_bucket", dropna=True)
                    .agg(
                        orders=("order_id", "count"),
                        avg_delay_min=("delivery_duration_min", "mean"),
                    )
                    .dropna()
                    .reset_index()
                )
                if not minute_bucket.empty:
                    minute_bucket["minute_bucket"] = pd.to_numeric(minute_bucket["minute_bucket"], errors="coerce")
                    minute_bucket = minute_bucket.dropna(subset=["minute_bucket"])

                    plt.figure(figsize=(10, 4))
                    sns.barplot(data=minute_bucket, x="minute_bucket", y="orders", color="#2563eb")
                    plt.title("Orders per 5-Minute Bucket")
                    plt.xlabel("Minute Bucket Start")
                    plt.ylabel("Orders")
                    plt.tight_layout()
                    plt.savefig(FIGURE_DIR / "orders_per_5min_bucket.png", dpi=150)
                    plt.close()

                    plt.figure(figsize=(10, 4))
                    plt.plot(minute_bucket["minute_bucket"], minute_bucket["avg_delay_min"], marker="o", color="#ef4444")
                    plt.title("Average Delay per 5-Minute Bucket")
                    plt.xlabel("Minute Bucket Start")
                    plt.ylabel("Average Delivery Duration (min)")
                    plt.tight_layout()
                    plt.savefig(FIGURE_DIR / "avg_delay_per_5min_bucket.png", dpi=150)
                    plt.close()

    if {"product_category", "delivery_duration_min", "rating"}.issubset(cleaned.columns):
        cat = (
            cleaned.groupby("product_category", dropna=False)[["delivery_duration_min", "rating"]]
            .mean()
            .sort_values("delivery_duration_min", ascending=False)
            .head(10)
            .reset_index()
        )
        if not cat.empty:
            plt.figure(figsize=(11, 5))
            sns.barplot(data=cat, x="product_category", y="delivery_duration_min", color="#ea580c")
            plt.title("Top Categories by Average Delivery Delay")
            plt.xlabel("Product Category")
            plt.ylabel("Average Delivery Duration (min)")
            plt.xticks(rotation=35, ha="right")
            plt.tight_layout()
            plt.savefig(FIGURE_DIR / "category_avg_delay.png", dpi=150)
            plt.close()

            plt.figure(figsize=(11, 5))
            sns.barplot(data=cat.sort_values("rating", ascending=True), x="product_category", y="rating", color="#0f766e")
            plt.title("Category Rating Comparison")
            plt.xlabel("Product Category")
            plt.ylabel("Average Rating")
            plt.xticks(rotation=35, ha="right")
            plt.tight_layout()
            plt.savefig(FIGURE_DIR / "category_avg_rating.png", dpi=150)
            plt.close()

    if {"order_value_inr", "rating"}.issubset(cleaned.columns):
        sample = cleaned[["order_value_inr", "rating"]].dropna().sample(
            n=min(5000, cleaned[["order_value_inr", "rating"]].dropna().shape[0]),
            random_state=42,
        )
        if not sample.empty:
            plt.figure(figsize=(9, 5))
            sns.scatterplot(data=sample, x="order_value_inr", y="rating", alpha=0.35, color="#7c3aed")
            plt.title("Order Value vs Rating")
            plt.xlabel("Order Value (INR)")
            plt.ylabel("Rating")
            plt.tight_layout()
            plt.savefig(FIGURE_DIR / "order_value_vs_rating.png", dpi=150)
            plt.close()

    if {"refund_requested", "delivery_duration_min"}.issubset(cleaned.columns):
        refund_delay = (
            cleaned.assign(refund_yes=cleaned["refund_requested"].eq("Yes").astype(int))
            .groupby("duration_band", dropna=False)["refund_yes"]
            .mean()
            .mul(100)
            .reset_index(name="refund_rate_pct")
        )
        if not refund_delay.empty:
            plt.figure(figsize=(9, 5))
            sns.barplot(data=refund_delay, x="duration_band", y="refund_rate_pct", color="#dc2626")
            plt.title("Refund Rate by Delivery Duration Band")
            plt.xlabel("Delivery Duration Band (min)")
            plt.ylabel("Refund Rate (%)")
            plt.tight_layout()
            plt.savefig(FIGURE_DIR / "refund_rate_by_duration_band.png", dpi=150)
            plt.close()

    corr_cols = [col for col in ["delivery_duration_min", "rating", "order_value_inr", "order_minute_of_day"] if col in cleaned.columns]
    if len(corr_cols) >= 2:
        corr_matrix = cleaned[corr_cols].corr(numeric_only=True)
        plt.figure(figsize=(7, 5))
        sns.heatmap(corr_matrix, cmap="coolwarm", center=0, annot=True, fmt=".2f", linewidths=0.5)
        plt.title("Correlation Heatmap")
        plt.tight_layout()
        plt.savefig(FIGURE_DIR / "correlation_heatmap.png", dpi=150)
        plt.close()


def main() -> None:
    if not RAW_FILE.exists():
        raise FileNotFoundError(f"Source file not found: {RAW_FILE}")

    # End-to-end pipeline: load raw -> clean -> save outputs -> report key metrics.
    raw = load_data(RAW_FILE)
    cleaned = clean_data(raw)
    cleaned.to_csv(CLEAN_FILE, index=False)

    summary_text = write_summary(cleaned, raw, REPORT_FILE)
    make_plots(cleaned)

    duration_rating_corr = cleaned[["delivery_duration_min", "rating"]].corr().iloc[0, 1]
    late_share = cleaned["delay_category"].eq("Late").mean() * 100

    print("Cleaned file written to:", CLEAN_FILE)
    print("Report written to:", REPORT_FILE)
    print("Figures written to:", FIGURE_DIR)
    print(f"Orders analyzed: {len(cleaned):,}")
    print(f"Average delivery duration: {cleaned['delivery_duration_min'].mean():.2f} minutes")
    print(f"Average rating: {cleaned['rating'].mean():.2f} / 5")
    print(f"Late share (>30 min): {late_share:.2f}%")
    print(f"Duration vs rating correlation: {duration_rating_corr:.4f}")
    if {"order_hour", "delivery_duration_min"}.issubset(cleaned.columns):
        hour_delay = cleaned.groupby("order_hour", dropna=True)["delivery_duration_min"].mean()
        if not hour_delay.empty:
            peak_hour = int(hour_delay.idxmax())
            print(f"Peak delay hour: {peak_hour:02d}:00 ({hour_delay.max():.2f} min)")
            if hour_delay.index.nunique() <= 1:
                print("Note: order hour is concentrated in a single bucket; source time appears minute-second formatted")
    print("\nSummary preview:\n")
    print(summary_text)


if __name__ == "__main__":
    main()
